### ISSUE TITLE
训练过程中报错

### ISSUE THREAD

**Issue by lindadamama** [fudan-zvg/SeaFormer#9]
下面是日志
2023-03-01 00:46:04,384 - mmseg - INFO - Iter [3700/80000]	lr: 1.908e-04, eta: 3:57:00, time: 0.177, data_time: 0.045, memory: 1529, decode.loss_ce: 0.2111, decode.acc_seg: 77.1174, loss: 0.2111
2023-03-01 00:46:13,141 - mmseg - INFO - Iter [3750/80000]	lr: 1.906e-04, eta: 3:56:39, time: 0.175, data_time: 0.045, memory: 1529, decode.loss_ce: 0.2195, decode.acc_seg: 79.2978, loss: 0.2195
2023-03-01 00:46:21,851 - mmseg - INFO - Iter [3800/80000]	lr: 1.905e-04, eta: 3:56:18, time: 0.174, data_time: 0.045, memory: 1529, decode.loss_ce: 0.2097, decode.acc_seg: 76.6177, loss: 0.2097
2023-03-01 00:46:30,523 - mmseg - INFO - Iter [3850/80000]	lr: 1.904e-04, eta: 3:55:56, time: 0.173, data_time: 0.045, memory: 1529, decode.loss_ce: 0.2044, decode.acc_seg: 75.5630, loss: 0.2044
2023-03-01 00:46:39,253 - mmseg - INFO - Iter [3900/80000]	lr: 1.903e-04, eta: 3:55:36, time: 0.175, data_time: 0.045, memory: 1529, decode.loss_ce: 0.1987, decode.acc_seg: 76.1465, loss: 0.1987
2023-03-01 00:46:48,201 - mmseg - INFO - Iter [3950/80000]	lr: 1.901e-04, eta: 3:55:20, time: 0.179, data_time: 0.045, memory: 1529, decode.loss_ce: 0.2033, decode.acc_seg: 75.5931, loss: 0.2033
2023-03-01 00:46:56,942 - mmseg - INFO - Saving checkpoint at 4000 iterations
2023-03-01 00:46:57,375 - mmseg - INFO - Exp name: seaformer_base_480x480_80k_2x8_pascalcontext.py
2023-03-01 00:46:57,375 - mmseg - INFO - Iter [4000/80000]	lr: 1.900e-04, eta: 3:55:09, time: 0.183, data_time: 0.045, memory: 1529, decode.loss_ce: 0.2205, decode.acc_seg: 77.2272, loss: 0.2205
[                                                  ] 0/25, elapsed: 0s, ETA:Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\A1057\anaconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\A1057\anaconda3\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\A1057\anaconda3\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\A1057\anaconda3\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\A1057\anaconda3\lib\runpy.py", line 288, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\A1057\anaconda3\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\A1057\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\11.3\Seaformer\tools\train.py", line 9, in <module>
    import mmcv
  File "C:\Users\A1057\anaconda3\lib\site-packages\mmcv\__init__.py", line 6, in <module>
    from .fileio import *
  File "C:\Users\A1057\anaconda3\lib\site-packages\mmcv\fileio\__init__.py", line 2, in <module>
    from .file_client import BaseStorageBackend, FileClient
  File "C:\Users\A1057\anaconda3\lib\site-packages\mmcv\fileio\file_client.py", line 15, in <module>
    from mmcv.utils.misc import has_method
  File "C:\Users\A1057\anaconda3\lib\site-packages\mmcv\utils\__init__.py", line 22, in <module>
    import torch
  File "C:\Users\A1057\anaconda3\lib\site-packages\torch\__init__.py", line 129, in <module>
    raise err
OSError: [WinError 1455] 页面文件太小，无法完成操作。 Error loading "C:\Users\A1057\anaconda3\lib\site-packages\torch\lib\shm.dll" or one of its dependencies.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\A1057\anaconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\A1057\anaconda3\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\A1057\anaconda3\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\A1057\anaconda3\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\A1057\anaconda3\lib\runpy.py", line 288, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\A1057\anaconda3\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\A1057\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\11.3\Seaformer\tools\train.py", line 9, in <module>
    import mmcv
  File "C:\Users\A1057\anaconda3\lib\site-packages\mmcv\__init__.py", line 6, in <module>
    from .fileio import *
  File "C:\Users\A1057\anaconda3\lib\site-packages\mmcv\fileio\__init__.py", line 2, in <module>
    from .file_client import BaseStorageBackend, FileClient
  File "C:\Users\A1057\anaconda3\lib\site-packages\mmcv\fileio\file_client.py", line 15, in <module>
    from mmcv.utils.misc import has_method
  File "C:\Users\A1057\anaconda3\lib\site-packages\mmcv\utils\__init__.py", line 22, in <module>
    import torch
  File "C:\Users\A1057\anaconda3\lib\site-packages\torch\__init__.py", line 129, in <module>
    raise err
OSError: [WinError 1455] 页面文件太小，无法完成操作。 Error loading "C:\Users\A1057\anaconda3\lib\site-packages\torch\lib\cublas64_11.dll" or one of its dependencies.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\A1057\anaconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\A1057\anaconda3\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\A1057\anaconda3\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\A1057\anaconda3\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\A1057\anaconda3\lib\runpy.py", line 288, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\A1057\anaconda3\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\A1057\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\11.3\Seaformer\tools\train.py", line 9, in <module>
    import mmcv
  File "C:\Users\A1057\anaconda3\lib\site-packages\mmcv\__init__.py", line 6, in <module>
    from .fileio import *
  File "C:\Users\A1057\anaconda3\lib\site-packages\mmcv\fileio\__init__.py", line 2, in <module>
    from .file_client import BaseStorageBackend, FileClient
  File "C:\Users\A1057\anaconda3\lib\site-packages\mmcv\fileio\file_client.py", line 15, in <module>
    from mmcv.utils.misc import has_method
  File "C:\Users\A1057\anaconda3\lib\site-packages\mmcv\utils\__init__.py", line 22, in <module>
    import torch
  File "C:\Users\A1057\anaconda3\lib\site-packages\torch\__init__.py", line 129, in <module>
    raise err
OSError: [WinError 1455] 页面文件太小，无法完成操作。 Error loading "C:\Users\A1057\anaconda3\lib\site-packages\torch\lib\cudnn_cnn_infer64_8.dll" or one of its dependencies.
C:\Users\A1057\anaconda3\lib\site-packages\mmcv\__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
Traceback (most recent call last):
  File "C:\Users\A1057\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 1163, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "C:\Users\A1057\anaconda3\lib\queue.py", line 179, in get
    raise Empty
_queue.Empty

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\11.3\Seaformer\tools\train.py", line 182, in <module>
    main()
  File "D:\11.3\Seaformer\tools\train.py", line 171, in main
    train_segmentor(
  File "D:\11.3\Seaformer\mmseg\apis\train.py", line 167, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "C:\Users\A1057\anaconda3\lib\site-packages\mmcv\runner\iter_based_runner.py", line 144, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "C:\Users\A1057\anaconda3\lib\site-packages\mmcv\runner\iter_based_runner.py", line 70, in train
    self.call_hook('after_train_iter')
  File "C:\Users\A1057\anaconda3\lib\site-packages\mmcv\runner\base_runner.py", line 317, in call_hook
    getattr(hook, fn_name)(self)
  File "C:\Users\A1057\anaconda3\lib\site-packages\mmcv\runner\hooks\evaluation.py", line 266, in after_train_iter
    self._do_evaluate(runner)
  File "D:\11.3\Seaformer\mmseg\core\evaluation\eval_hooks.py", line 49, in _do_evaluate
    results = single_gpu_test(
  File "D:\11.3\Seaformer\mmseg\apis\test.py", line 89, in single_gpu_test
    for batch_indices, data in zip(loader_indices, data_loader):
  File "C:\Users\A1057\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 681, in __next__
    data = self._next_data()
  File "C:\Users\A1057\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 1359, in _next_data
    idx, data = self._get_data()
  File "C:\Users\A1057\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 1315, in _get_data
    success, data = self._try_get_data()
  File "C:\Users\A1057\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 1176, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 14036, 8276, 17164) exited unexpectedly

Process finished with exit code 1

**Comment by lindadamama** [comment]
<img width="550" alt="屏幕截图 2023-03-01 005558" src="https://user-images.githubusercontent.com/48863486/221923122-2f83ca04-567b-48bb-961f-c71e3276f855.png">
还有个疑问,图片中的crop_size = (512, 512)指的是训练图片的大小吗？那么哪个是height哪个是width，还有img_scale=(2048, 512)是把小图片放大了吗？
